import React, { useState } from 'react';
import { Bot, RefreshCw, AlertCircle, ExternalLink } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { FinancialInputs, ScenarioResult, AIAnalysisResult } from '../types';
import { getAIAnalysis } from '../services/geminiService';

interface AIAdvisorProps {
  inputs: FinancialInputs;
  results: ScenarioResult;
}

export const AIAdvisor: React.FC<AIAdvisorProps> = ({ inputs, results }) => {
  const [result, setResult] = useState<AIAnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);

  const handleAnalyze = async () => {
    setLoading(true);
    const data = await getAIAnalysis(inputs, results);
    setResult(data);
    setLoading(false);
  };

  return (
    <div className="bg-gradient-to-br from-indigo-50 to-purple-50 rounded-xl p-6 border border-indigo-100 shadow-sm mt-6">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-indigo-600 rounded-lg">
            <Bot className="w-6 h-6 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-indigo-900">AI Financial Advisor</h3>
            <p className="text-xs text-indigo-600">Powered by Gemini 2.5 with Google Search</p>
          </div>
        </div>
        <button
          onClick={handleAnalyze}
          disabled={loading}
          className="flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition-colors disabled:opacity-50 text-sm font-medium shadow-sm"
        >
          {loading ? (
            <RefreshCw className="w-4 h-4 animate-spin" />
          ) : (
            <RefreshCw className="w-4 h-4" />
          )}
          {result ? 'Re-Analyze' : 'Analyze Scenario'}
        </button>
      </div>

      {!result && !loading && (
        <div className="text-sm text-indigo-800/70 p-4 bg-indigo-100/50 rounded-lg border border-indigo-200/50">
          Click "Analyze Scenario" to get a qualitative assessment of these two paths, covering tax nuances, risks, and hidden opportunities.
        </div>
      )}

      {loading && (
        <div className="space-y-3 animate-pulse">
          <div className="h-4 bg-indigo-200 rounded w-3/4"></div>
          <div className="h-4 bg-indigo-200 rounded w-1/2"></div>
          <div className="h-4 bg-indigo-200 rounded w-full"></div>
        </div>
      )}

      {result && !loading && (
        <>
          <div className="prose prose-indigo prose-sm max-w-none text-slate-700 mb-6">
             <ReactMarkdown>{result.analysis}</ReactMarkdown>
          </div>

          {result.sources.length > 0 && (
            <div className="border-t border-indigo-200 pt-3 mt-4">
              <h4 className="text-xs font-semibold text-indigo-900 mb-2 uppercase tracking-wide">Sources</h4>
              <ul className="space-y-1">
                {result.sources.map((source, index) => (
                  <li key={index}>
                    <a 
                      href={source.uri} 
                      target="_blank" 
                      rel="noopener noreferrer"
                      className="text-xs text-indigo-600 hover:text-indigo-800 hover:underline flex items-center gap-1 truncate"
                    >
                      <ExternalLink className="w-3 h-3 flex-shrink-0" />
                      {source.title}
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}
      
      <div className="mt-4 flex items-start gap-2 text-xs text-slate-500 bg-white p-3 rounded border border-slate-100">
        <AlertCircle className="w-4 h-4 text-slate-400 flex-shrink-0" />
        <p>
          This analysis is generated by an AI model and should not be considered professional tax advice. Always consult with a CPA or tax professional before making significant financial decisions.
        </p>
      </div>
    </div>
  );
};
